CREATE TABLE IF NOT EXISTS `#__cot_admin_forms` (
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`references` VARCHAR(13) NOT NULL,
`id_location` INT(11) NOT NULL,
`observer_name` VARCHAR(100) NOT NULL,
`observer_tel` VARCHAR(100) NOT NULL,
`observer_mail` VARCHAR(100) NOT NULL,
`informant_name` VARCHAR(100) NOT NULL,
`informant_tel` VARCHAR(100) NOT NULL,
`informant_mail` VARCHAR(100) NOT NULL,
`observation_date` DATE NOT NULL,
`observation_location` VARCHAR(100) NOT NULL,
`observation_region` VARCHAR(100) NOT NULL,
`observation_country` VARCHAR(100) NOT NULL,
`observation_latitude` VARCHAR(100) NOT NULL,
`observation_longitude` VARCHAR(100) NOT NULL,
`observation_mammal_number` VARCHAR(100) NOT NULL,
`observation_mammal_size` VARCHAR(100) NOT NULL,
`observation_mammal_sex` VARCHAR(100) NOT NULL,
`observation_mammal_spaces` VARCHAR(100) NOT NULL,
`observation_mammal_spaces_identification` VARCHAR(100) NOT NULL,
`observation_abnormalities` VARCHAR(250) NOT NULL,
`observation_levies` VARCHAR(250) NOT NULL,
`observation_mammal_state` VARCHAR(100) NOT NULL,
`observation_mammal_state_decomposition` VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
) DEFAULT COLLATE=utf8_general_ci;
